#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while read -r passwrd; do
  echo "$passwrd" | cut -d ':' -f1,3,6
done < "/etc/passwrd"
